/* Cached frames, full-episode video, and native-score decision inspection. */
'use strict';
const curveColors=['#087f8c','#db7c18','#c74936','#964334','#9c4dcc','#7158bf','#c25292','#2463b3','#343b46','#777c83'];
const curveEscape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function curveScale(value,scale){if(value===null||value===undefined||!Number.isFinite(value))return null;return 1/(1+Math.exp(-Math.max(-40,Math.min(40,(value-scale.threshold)/(scale.std||1)))));}
async function hydrateEpisodeCurves(){
 for(const root of document.querySelectorAll('[data-curve-url]:not([data-loaded])')){
  root.dataset.loaded='loading';
  try{
   const data=ROBOT_SITE.mapData((await import(root.dataset.curveUrl)).default);if(!root.isConnected)continue;if(!data.episodes.length)throw new Error('No completed curves');
   root.classList.toggle('paired-camera-curves',data.media_layout==='paired');
   const methods=data.methods,label=m=>data.method_labels?.[m]||m,active=new Set(data.default_methods||methods);let currentIndex=0,lastEpisode=-1,updatePoint=()=>{};
   root.innerHTML=`<div class="curve-controls"><label>Episode<select aria-label="Select episode">${data.episodes.map((e,i)=>`<option value="${i}" data-episode-id="${curveEscape(e.id)}">${curveEscape(e.title||e.id)}</option>`).join('')}</select></label><label>Plot view<select aria-label="Select plot view">${data.raw_axes?'<option value="raw_axes">Raw scores · separate axes</option>':'<option value="overlay">All models · frozen threshold scale</option>'}${methods.includes('DT')?'<option value="raw_dt">DT · raw expected distance</option>':''}</select></label>${data.independent_series&&!data.offline_full_trajectory?'<label>Timeline<select aria-label="Select timeline"><option value="query">Prediction time</option><option value="target">Scored frame · VOC</option></select></label>':''}</div><p class="curve-description"></p><div class="curve-media"><figure class="curve-goal"><figcaption>${curveEscape(data.goal_caption||'Goal image · PSI + DINO')}</figcaption><a target="_blank" rel="noopener"><img alt="Exact supplied visual goal"></a><p class="curve-goal-kind"></p></figure><figure class="curve-current"><figcaption>${curveEscape(data.current_caption||'Observation at selected sample')}</figcaption><a target="_blank" rel="noopener"><img alt="Current observation used for this model sample"></a><p class="curve-frame-label"></p></figure></div><p class="curve-instruction subtle"></p><label class="curve-scrubber">Inspect time <output></output><input type="range" min="0" step="1" aria-label="Inspect episode time"></label><div class="curve-legend" aria-label="Toggle models">${methods.map((m,i)=>`<button type="button" data-method="${curveEscape(m)}" aria-pressed="${active.has(m)}" style="--curve-color:${curveColors[i%curveColors.length]}">${curveEscape(label(m))}</button>`).join('')}</div><div class="curve-chart"></div><div class="curve-review"><div class="curve-playback"><div class="curve-play-controls"><button type="button" class="curve-play">▶ Play selected episode</button><span class="subtle">Video playback and the graph share a time cursor.</span></div><div class="curve-video-panel" hidden><video controls playsinline preload="none"></video><p class="subtle">${curveEscape(data.video_note||'The video shows the full selected episode. Predictions are sampled; the inspector shows the nearest scored observation.')}</p></div></div><aside class="curve-inspector"><label>Inspect completion decision<select aria-label="Inspect model">${methods.map(m=>`<option value="${curveEscape(m)}">${curveEscape(label(m))}</option>`).join('')}</select></label><div class="curve-decision"></div><p class="curve-sample-sequence subtle"></p><div class="curve-evaluator"><strong>Evaluator judgment</strong><p class="curve-outcome"></p><p class="curve-evaluator-sample"></p></div></aside></div><div class="curve-readout" aria-live="polite"></div><p class="subtle curve-scale-note"></p>`;
   const select=root.querySelector('[aria-label="Select episode"]'),view=root.querySelector('[aria-label="Select plot view"]'),inspect=root.querySelector('[aria-label="Inspect model"]'),slider=root.querySelector('input[type="range"]'),chart=root.querySelector('.curve-chart'),video=root.querySelector('video'),play=root.querySelector('.curve-play'),panel=root.querySelector('.curve-video-panel');
   const timeline=root.querySelector('[aria-label="Select timeline"]');
   const noCutoff=['voc','auroc'].includes(data.evaluation_kind);
   if(noCutoff){root.querySelector('.curve-decision').hidden=true;root.querySelector('.curve-evaluator').hidden=data.evaluation_kind==='voc';root.querySelector('.curve-inspector label').firstChild.textContent='Inspect model score';}
   function seekVideo(ep,x){if(!ep.video_x)return;let best=0;ep.video_x.forEach((v,i)=>{if(Math.abs(v-x)<Math.abs(ep.video_x[best]-x))best=i;});const t=best/ep.video_fps;if(video.readyState>=1)video.currentTime=t;else video.addEventListener('loadedmetadata',()=>{video.currentTime=t;},{once:true});}
   function draw(){
    const selected=Number(select.value),ep=data.episodes[selected],pts=ep.points,raw=view.value==='raw_dt',rawAxes=view.value==='raw_axes';
    const queryTime=timeline?.value==='query',plotX=p=>queryTime&&p.query_frame!==undefined?(ep.video_x?.[p.query_frame]??p.x):p.x;
    if(selected!==lastEpisode){video.pause();panel.hidden=true;play.textContent='▶ Play selected episode';video.innerHTML=ep.video_url?`${ep.video_webm_url?`<source src="${curveEscape(ep.video_webm_url)}" type="video/webm">`:''}<source src="${curveEscape(ep.video_url)}" type="video/mp4">`:'';video.load();play.disabled=!ep.video_url;lastEpisode=selected;currentIndex=pts.length-1;}
    if(raw)inspect.value='DT';inspect.disabled=raw;
    const values=pts.map(p=>p.scores.DT).filter(v=>v!==null&&Number.isFinite(v)).map(v=>-v),ymax=raw?Math.max(5,...values)*1.05:1,threshold=raw&&!noCutoff?-data.scale.DT.threshold:.5;
    root.querySelector('.curve-legend').style.display=raw?'none':'';
    root.querySelector('.curve-scale-note').textContent=rawAxes?data.raw_axes_note:raw&&noCutoff?'Native expected DT bin: lower means closer. No classification cutoff; bins are not seconds.':raw?`Native expected DT bin: lower means closer. Dashed line: fixed ABC success cutoff ${threshold.toFixed(3)} bins. Bins are not seconds. Axis range adapts; scores and decisions stay unchanged.`:'Overlay = sigmoid((raw score − cutoff) / ABC development SD). The dashed 0.5 line is the completion decision boundary, not 50% task progress. Scores far below their cutoff compress near zero; use raw DT to inspect distance directly. Lines join sampled observations.';
    if(data.independent_series)root.querySelector('.curve-scale-note').textContent=(queryTime?'X-axis: prediction request time (end of the input sequence), using actual episode frames. Robometer may score an earlier frame within that sequence; this curve is not current-frame progress.':'X-axis: the actual frame being scored. Robometer ends around 57% because its released evaluator selects earlier frames from each input sequence.')+' VOC is unchanged and uses scored-frame timestamps, not the display timeline. PSI excludes its final point from VOC. Native score axes; no rescaling.';
    if(data.offline_full_trajectory)root.querySelector('.curve-scale-note').textContent=data.raw_axes_note;
    root.querySelector('.curve-description').textContent=ep.description||'';
    const goal=root.querySelector('.curve-goal');goal.querySelector('a').href=ep.goal_url;goal.querySelector('img').src=ep.goal_url;root.querySelector('.curve-goal-kind').textContent=ep.goal_kind||ep.goal_description||'Successful visual goal';
    root.querySelector('.curve-outcome').textContent='Final episode: '+(ep.outcome||ep.quality_label||'see results');
    root.querySelector('.curve-instruction').textContent=ep.task?'Robometer receives the instruction “'+ep.task+'” and prefix observations; it does not receive the goal image.':'';
    slider.max=pts.length-1;
    const W=1040,H=390,L=65,R=rawAxes?(data.axis_order?Math.max(20,110*data.axis_order.length):200):20,T=20,B=55,pw=W-L-R,ph=H-T-B,xmax=Math.max(...(ep.video_x?.length?ep.video_x:pts.map(p=>p.x))),px=x=>L+x/(xmax||1)*pw,py=y=>T+(1-y/ymax)*ph;
    let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Model scores across ${curveEscape(ep.title||ep.id)}">`;
    for(const frac of [0,.25,.5,.75,1]){const y=frac*ymax;svg+=`<line x1="${L}" y1="${py(y)}" x2="${W-R}" y2="${py(y)}" stroke="#e3e7ed"/><text x="${L-12}" y="${py(y)+4}" text-anchor="end">${y.toFixed(raw?1:2)}</text>`;}
    if(!rawAxes&&!noCutoff)svg+=`<line x1="${L}" y1="${py(threshold)}" x2="${W-R}" y2="${py(threshold)}" stroke="#788597" stroke-dasharray="6 5"/>`;
    for(const frac of [0,.25,.5,.75,1])svg+=`<text x="${px(frac*xmax)}" y="${H-28}" text-anchor="middle">${ep.x_label==='Seconds'?(frac*xmax).toFixed(1):Math.round(frac*xmax*100)+'%'}</text>`;
    svg+=`<text x="${L+pw/2}" y="${H-5}" text-anchor="middle">${curveEscape(data.independent_series?(queryTime?'Prediction time · position in episode':'Scored frame · position in episode'):(ep.x_label||'Position in released video'))}</text><text transform="translate(16 ${T+ph/2}) rotate(-90)" text-anchor="middle">${raw?'DT expected bin · lower is closer':rawAxes?(data.primary_axis_label||'Robometer / native 0–1 outputs'):'Scaled completion evidence'}</text>`;
    for(const event of ep.events||[])svg+=`<line x1="${px(event.x)}" y1="${T}" x2="${px(event.x)}" y2="${H-B}" stroke="#b09562" stroke-dasharray="3 4"/><text x="${px(event.x)+4}" y="${T+12}" class="curve-event">${curveEscape(event.label)}</text>`;
    const rawY=(value,axis)=>T+(1-(value-axis.min)/(axis.max-axis.min))*ph;
    if(rawAxes){
     for(const [name,offset,color,label] of [['surprisal',0,'#a64f23','Negative surprisal ↑'],['dt',96,'#087f8c','DT bins ↓']]){
      if(data.axis_order&&!data.axis_order.includes(name))continue;const axis=data.raw_axes[name],x=W-R+(data.axis_order?96*data.axis_order.indexOf(name):offset);
      svg+=`<line x1="${x}" x2="${x}" y1="${T}" y2="${H-B}" stroke="${color}"/>`;
      for(const f of [0,.25,.5,.75,1]){const v=axis.min+f*(axis.max-axis.min);svg+=`<line x1="${x}" x2="${x+5}" y1="${rawY(v,axis)}" y2="${rawY(v,axis)}" stroke="${color}"/><text x="${x+9}" y="${rawY(v,axis)+4}" fill="${color}">${v.toFixed(1)}</text>`;}
      svg+=`<text transform="translate(${x+65} ${T+ph/2}) rotate(-90)" text-anchor="middle" fill="${color}">${curveEscape(axis.label||label)}</text>`;
     }
    }
    methods.forEach((m,i)=>{if(raw?m!=='DT':!active.has(m))return;let path='',started=false;for(const p of (ep.model_series?.[m]||pts)){const value=p.scores[m];if(value===null||value===undefined){started=false;continue;}const y=raw?py(-value):rawAxes?(m==='DT'?rawY(-value,data.raw_axes.dt):/^[SH][135]$/.test(m)?rawY(value,data.raw_axes.surprisal):py(value)):py(curveScale(value,data.scale[m]));path+=`${started?'L':'M'}${px(plotX(p)).toFixed(2)},${y.toFixed(2)} `;started=true;}svg+=`<path data-model="${curveEscape(m)}" d="${path}" fill="none" stroke="${curveColors[i%curveColors.length]}" stroke-width="${m===inspect.value?3.5:2.2}" stroke-dasharray="${i===2?'7 3':i===3?'2 3':i>=4&&i<=6?'9 3 2 3':''}"/>`;});
    svg+=`<line class="curve-cursor" x1="0" x2="0" y1="${T}" y2="${H-B}" stroke="#1c2838"/><rect class="curve-hit" x="${L}" y="${T}" width="${pw}" height="${ph}" fill="transparent"/></svg>`;chart.innerHTML=svg;
    const sampleFor=(m,p)=>{const series=ep.model_series?.[m];return series?.length?series.reduce((best,q)=>Math.abs(plotX(q)-p.x)<Math.abs(plotX(best)-p.x)?q:best,series[0]):p;};
    updatePoint=(index,cursorX)=>{
     currentIndex=Math.max(0,Math.min(pts.length-1,index));slider.value=currentIndex;const p=pts[currentIndex],m=inspect.value,measured=sampleFor(m,p),s=measured.scores[m],cut=noCutoff?null:data.scale[m].threshold,available=s!==null&&s!==undefined;
     const cursor=chart.querySelector('.curve-cursor');cursor.setAttribute('x1',px(cursorX??p.x));cursor.setAttribute('x2',px(cursorX??p.x));
     const when=ep.x_label==='Seconds'?`${p.x.toFixed(2)} s`:`${(p.x*100).toFixed(1)}% of released video`;
     root.querySelector('.curve-evaluator-sample').textContent=p.completion!==undefined?`At selected sample: ${(100*p.completion).toFixed(0)}% of mugs satisfy the ABC rule: upright (vertical alignment ≥ 0.95) and no more than 3 cm above their initial height. Final success requires all mugs to satisfy it.`:'The public dataset supplies an episode-level label; no frame-level success judgment is available here.';
     root.querySelector('.curve-scrubber output').textContent=when;root.querySelector('.curve-frame-label').textContent=`Frame ${p.frame} · ${when}${p.completion!==undefined?' · measured completion '+p.completion.toFixed(2):''}`;
     const current=root.querySelector('.curve-current');if(p.image_url&&current.querySelector('img').getAttribute('src')!==p.image_url){current.querySelector('img').src=p.image_url;current.querySelector('a').href=p.image_url;}
     const seqNote=root.querySelector('.curve-sample-sequence');if(available&&measured.goal_schedule==='remaining'&&!m.startsWith('Robometer')&&m!=='DINOv2'){const dt=data.method_sequences?.DT||'rgb0,rgb0^g,dt0';const h=Number(m.slice(-1));const seq=m==='DT'?dt:Array.from({length:h},(_,i)=>'rgb'+i).concat('rgb'+(h-1+measured.remaining_slots)).join(',');seqNote.textContent='Sequence here: '+(m.startsWith('DT +')?dt+' and ':'')+seq+(m==='DT'?'':' · R = '+measured.remaining_slots+' slots');}else if(available&&m==='Robometer progress'&&measured.query_frame!==undefined){seqNote.textContent='Released output: target frame '+measured.frame+'; input prefix ends at frame '+measured.query_frame+'.';}else seqNote.textContent='';
     if(!noCutoff){
     const predicted=available&&s>=cut;const rule=m==='DT'?`${(-s).toFixed(4)} ${predicted?'≤':'>'} ${(-cut).toFixed(4)} bins`:`${s?.toFixed(5)??'—'} ${predicted?'≥':'<'} ${cut.toFixed(5)}`;
     root.querySelector('.curve-decision').innerHTML=available?`<span class="curve-prediction ${predicted?'complete':'incomplete'}">${predicted?'Predicted complete':'Predicted incomplete'}</span><strong>${curveEscape(m)}</strong><code>${rule}</code><span>${m==='DT'?'Expected distance ≤ cutoff':'Raw score ≥ cutoff'} means complete.</span><small>At this observation · fixed ABC cutoff</small>`:'<strong>History unavailable</strong><p>This sample has too few observations for '+curveEscape(m)+'.</p>';
     }
     root.querySelector('.curve-readout').innerHTML=`<strong>Sampled frame ${p.frame}</strong><div>${methods.filter(m=>raw?m==='DT':active.has(m)).map(m=>{const q=sampleFor(m,p);return `<span>${curveEscape(label(m))}${data.independent_series?' · scored frame '+q.frame+(q.query_frame!==undefined?' · input ends '+q.query_frame:''):''}: ${q.scores[m]==null?'history unavailable':q.scores[m].toFixed(4)}</span>`;}).join('')}</div><small>${rawAxes||noCutoff?'Raw model scores. DT is stored as negative distance; the DT axis shows positive bins.':'Raw scores, before display scaling. DT score is negative expected distance.'}</small>`;
    };
    function pointAt(event){const rect=chart.querySelector('svg').getBoundingClientRect(),x=((event.clientX-rect.left)*W/rect.width-L)/pw*xmax;let i=0;pts.forEach((p,j)=>{if(Math.abs(p.x-x)<Math.abs(pts[i].x-x))i=j;});return i;}
    chart.querySelector('.curve-hit').addEventListener('pointermove',event=>{if(video.paused)updatePoint(pointAt(event));});
    chart.querySelector('.curve-hit').addEventListener('click',event=>{const i=pointAt(event);video.pause();updatePoint(i);if(!panel.hidden)seekVideo(ep,pts[i].x);});
    updatePoint(currentIndex);
   }
   slider.addEventListener('input',()=>{video.pause();updatePoint(Number(slider.value));const ep=data.episodes[Number(select.value)];if(!panel.hidden)seekVideo(ep,ep.points[currentIndex].x);});
   play.addEventListener('click',async()=>{if(panel.hidden){panel.hidden=false;video.load();video.currentTime=0;}if(video.paused){try{await video.play();}catch(e){root.querySelector('.curve-readout').textContent='Use the video controls to start playback.';}}else video.pause();});
   video.addEventListener('play',()=>{play.textContent='Ⅱ Pause episode';});video.addEventListener('pause',()=>{play.textContent='▶ Play selected episode';});
   video.addEventListener('timeupdate',()=>{if(panel.hidden)return;const ep=data.episodes[Number(select.value)];if(!ep.video_x?.length)return;const x=ep.video_x[Math.min(ep.video_x.length-1,Math.floor(video.currentTime*ep.video_fps))];let i=0;ep.points.forEach((p,j)=>{if(Math.abs(p.x-x)<Math.abs(ep.points[i].x-x))i=j;});updatePoint(i,x);});
   timeline?.addEventListener('change',draw);
   select.addEventListener('change',draw);view.addEventListener('change',draw);inspect.addEventListener('change',draw);
   root.querySelectorAll('[data-method]').forEach(button=>button.addEventListener('click',()=>{const m=button.dataset.method;if(active.has(m))active.delete(m);else active.add(m);button.setAttribute('aria-pressed',String(active.has(m)));draw();}));
   draw();root.dataset.loaded='true';
  }catch(error){root.textContent='Episode curves could not load: '+error.message;root.dataset.loaded='error';}
 }
}
