// Seating is transcribed from the owner's whiteboard, not inferred from faces.
// Coordinates are schematic, in arbitrary scene units; they are not surveyed.
// Unknown biographies and portraits stay explicit rather than guessed.
export const PEOPLE = [
  {
    id: "dan",
    name: "Dan Yamins",
    short: "Dan",
    initials: "DY",
    role: "Principal investigator",
    area: "NeuroAI",
    tags: ["NeuroAI", "Vision", "Learning"],
    bio: "Leads Stanford’s NeuroAI Lab, studying intelligence through computational models of the brain and advances in artificial intelligence. Associate Professor of Psychology and Computer Science.",
    photo: "yamins.jpg",
    website: "https://stanford.edu/~yamins/",
    source: "https://psychology.stanford.edu/people/daniel-yamins",
    sourceLabel: "Stanford Psychology",
    seat: {
      x: -1.1,
      z: 6.7,
      rotation: 0,
      shape: "corner",
      label: "Front · L-shaped workstation",
    },
  },
  {
    id: "klemen",
    name: "Klemen Kotar",
    short: "Klemen",
    initials: "KK",
    role: "PhD candidate · Computer Science",
    area: "World models",
    tags: ["World models", "Robotics", "PSI"],
    bio: "Builds autoregressive world models that learn physical structure from video and can be prompted to perceive, predict, and act. Works on the PSI model family and robotics.",
    photo: "klemen.jpg",
    website: "https://klemenkotar.github.io/",
    source: "https://klemenkotar.github.io/",
    sourceLabel: "Personal website",
    seat: {
      x: 4.65,
      z: 5.5,
      rotation: -0.45,
      label: "Right side · curved workstation",
    },
  },
  {
    id: "rahul",
    name: "Rahul Venkatesh",
    short: "Rahul",
    initials: "RV",
    role: "PhD student · Computer Science",
    area: "World models",
    tags: ["World models", "Physical understanding", "3D vision"],
    bio: "Studies physical understanding through computer vision and world modeling, including object representations, counterfactual prediction, and 3D scene understanding.",
    photo: "rahul.jpg",
    website: "https://rahulvenkk.github.io/",
    source: "https://rahulvenkk.github.io/",
    sourceLabel: "Personal website",
    seat: {
      x: 4.1,
      z: 2.2,
      rotation: Math.PI / 2,
      label: "Right-side island · inner desk",
    },
  },
  {
    id: "atlas",
    name: "Atlas Kazemian",
    short: "Atlas",
    initials: "AK",
    role: "PhD student",
    area: "World models",
    tags: ["World models", "Robotics", "Neuroscience"],
    bio: "Develops world models as pretraining for generalist robot policies, and explores how they can explain human knowledge of the physical world and intelligent behavior.",
    photo: "atlas.jpg",
    website: "https://akazemian.github.io/personal_profile/",
    source: "https://akazemian.github.io/personal_profile/",
    sourceLabel: "Personal website",
    seat: {
      x: 1.0,
      z: -3.1,
      rotation: Math.PI,
      label: "Main desks · across from Gia",
    },
  },
  {
    id: "yifan",
    name: "Yifan",
    short: "Yifan",
    initials: "Y",
    role: "Profile to be confirmed",
    area: "Profile pending",
    tags: [],
    bio: "Desk identified in the lab sketch. A full name, public profile, and research summary still need to be confirmed.",
    photo: null,
    website: null,
    source: null,
    sourceLabel: null,
    pending: true,
    seat: {
      x: -4.35,
      z: 2.35,
      rotation: 0,
      label: "Window side · beside Lilian",
    },
  },
  {
    id: "baihan",
    name: "Baihan Zhang",
    short: "Baihan",
    initials: "BZ",
    role: "Research profile pending",
    area: "Profile pending",
    tags: [],
    bio: "A member of the lab’s shared workspace. A verified research biography and portrait are still being added.",
    photo: null,
    website: null,
    source: null,
    sourceLabel: null,
    pending: true,
    seat: {
      x: 1.0,
      z: 1.5,
      rotation: Math.PI,
      label: "Main desks · across from Lilian",
    },
  },
  {
    id: "gia",
    name: "Gia Ancone",
    short: "Gia",
    initials: "GA",
    role: "Student · Computer Science",
    area: "World models",
    tags: ["World models", "Robotics", "Physics"],
    bio: "Works on PSI world modeling for robotics and object understanding. Her interests connect computer vision with physics, from physical representations to foundation models.",
    photo: "gia.jpg",
    website: "https://giaancone.com/",
    source: "https://giaancone.com/",
    sourceLabel: "Personal website",
    seat: {
      x: -1.4,
      z: -3.1,
      rotation: 0,
      label: "Main desks · across from Atlas",
    },
  },
  {
    id: "imran",
    name: "Imran Thobani",
    short: "Imran",
    initials: "IT",
    role: "Postdoctoral scholar",
    area: "Neuroscience",
    tags: ["Brain models", "Neuroscience", "Model–brain comparison"],
    bio: "Develops large-scale foundation models of the brain for scientific understanding and biomedical applications, working with NeuroAI and the Enigma Project.",
    photo: "imran.jpg",
    website: "https://imranthobani.com/",
    source: "https://imranthobani.com/",
    sourceLabel: "Personal website",
    seat: {
      x: 6.0,
      z: 2.2,
      rotation: -Math.PI / 2,
      label: "Right-side island · outer desk",
    },
  },
  {
    id: "cliona",
    name: "Clíona O’Doherty",
    short: "Clíona",
    initials: "CO",
    role: "Postdoctoral scholar",
    area: "Neuroscience",
    tags: ["Development", "Infant learning", "Neuroimaging"],
    bio: "Studies how infants learn so efficiently, combining cognitive computational methods, neuroimaging, and AI to understand the developing mind.",
    photo: "cliona.webp",
    website: "https://psychology.stanford.edu/people/cliona-o-doherty",
    source: "https://psychology.stanford.edu/people/cliona-o-doherty",
    sourceLabel: "Stanford Psychology",
    seat: {
      x: -4.35,
      z: 0.15,
      rotation: Math.PI / 2,
      label: "Window side · beside Kristine’s desk",
    },
  },
  {
    id: "seojin",
    name: "Seojin Lee",
    short: "Seojin",
    initials: "SL",
    role: "PhD student · Psychology",
    area: "Neuroscience",
    tags: ["Vision", "Cortical organization", "Development"],
    bio: "Studies how the visual system organizes before visual experience, using retinal-wave models and topographic neural networks to connect efficient wiring with visual learning.",
    photo: "seojin.webp",
    website: "https://slee20512.github.io/",
    source: "https://slee20512.github.io/",
    sourceLabel: "Personal website",
    seat: {
      x: 1.0,
      z: -0.5,
      rotation: Math.PI,
      label: "Main desks · across from Kristine’s desk",
    },
  },
  {
    id: "yash",
    name: "Yash Shah",
    short: "Yash",
    initials: "YS",
    role: "PhD student · Computer Science",
    area: "Neuroscience",
    tags: ["Cortical organization", "Vision", "Development"],
    bio: "Uses deep neural networks to study the functional and spatial organization of the brain, and how learning constraints and experience shape that organization.",
    photo: "yash.jpg",
    website: "https://ynshah3.github.io/",
    source: "https://ynshah3.github.io/",
    sourceLabel: "Personal website",
    seat: {
      x: 1.0,
      z: 4.15,
      rotation: Math.PI,
      label: "Front main desks · across from Khai’s desk",
    },
  },
  {
    id: "lilian",
    name: "Lilian Naing Chen",
    short: "Lilian",
    initials: "LC",
    role: "MS student · Computer Science",
    area: "World models",
    tags: ["World models", "Object understanding", "PSI"],
    bio: "Works on visual world models and physical scene understanding, including controllable prediction and object representations. Studies AI in Stanford’s coterminal computer science program.",
    photo: "liliang.jpg",
    website: "https://web.stanford.edu/~lilianch/",
    source: "https://web.stanford.edu/~lilianch/",
    sourceLabel: "Personal website",
    seat: {
      x: -1.4,
      z: 1.5,
      rotation: 0,
      label: "Main desks · across from Baihan",
    },
  },
  {
    id: "greyson",
    name: "Greyson Brothers",
    short: "Greyson",
    initials: "GB",
    role: "Incoming PhD student · Computer Science",
    area: "Learning",
    tags: ["Continual learning", "Memory", "Reinforcement learning"],
    bio: "Studies efficient and continual learning, attention, memory, and reinforcement learning, aiming for systems that learn rapidly through ongoing interactions in the real world.",
    photo: "greyson.png",
    website: "https://agbrothers.github.io/",
    source: "https://agbrothers.github.io/",
    sourceLabel: "Personal website",
    seat: {
      x: 1.0,
      z: -5.65,
      rotation: Math.PI,
      label: "Far main desks · across from Arjun",
    },
  },
  {
    id: "arjun",
    name: "Arjun Chandra",
    short: "Arjun",
    initials: "AC",
    role: "PhD student · Computer Science",
    area: "Learning",
    tags: ["Machine learning", "Cognition", "Development"],
    bio: "Works at the intersection of machine learning, cognitive science, and neuroscience, with research on developmentally inspired visual learning and transformer reasoning.",
    photo: "arjun.jpg",
    website: "https://arjunchandra2.github.io/",
    source: "https://arjunchandra2.github.io/",
    sourceLabel: "Personal website",
    seat: {
      x: -1.4,
      z: -5.65,
      rotation: 0,
      label: "Far main desks · across from Greyson",
    },
  },
  {
    id: "khai",
    name: "Khai Loong Aw",
    short: "Khai",
    initials: "KA",
    role: "PhD candidate · Computer Science",
    area: "World models",
    tags: ["World models", "Vision–language", "Development"],
    bio: "Builds world models and vision–language models for flexible, data-efficient learning, and uses them to study development, cognition, and the brain.",
    photo: "khai.jpg",
    website: "https://awwkl.github.io/",
    source: "https://awwkl.github.io/",
    sourceLabel: "Personal website",
    seat: {
      x: -1.4,
      z: 4.15,
      rotation: 0,
      label: "Front main desks · across from Yash",
    },
  },
  {
    id: "kristine",
    name: "Kristine Zheng",
    short: "Kristine",
    initials: "KZ",
    role: "PhD student · Computer Science",
    area: "Learning",
    tags: ["Visual cognition", "Physical reasoning", "Learning"],
    bio: "Studies how people learn from and interact with visual experiences, including physical reasoning, games, collaborative sketching, and classroom learning.",
    photo: "kristine.png",
    website: "https://kristinezheng.github.io/",
    source: "https://kristinezheng.github.io/",
    sourceLabel: "Personal website",
    seat: {
      x: -1.4,
      z: -0.5,
      rotation: 0,
      label: "Main desks · across from Seojin",
    },
  },
];

// Preserve additional labels visible in the sketch without inventing identities.
export const EXTRA_DESKS = [
  { id: "unassigned-a", short: "Unlabeled", x: -1.4, z: -8.1, rotation: 0 },
  {
    id: "unassigned-b",
    short: "Unlabeled",
    x: 1.0,
    z: -8.1,
    rotation: Math.PI,
  },
];

export const LANDMARKS = [
  {
    id: "rene",
    name: "RENE",
    short: "RENE · YAM",
    x: 5.3,
    z: 8.4,
    height: 2,
    description: "The lab’s YAM robot setup—not a person or an available desk.",
  },
];

export const AREAS = {
  NeuroAI: "#6d7b64",
  "World models": "#ca784e",
  Neuroscience: "#638d98",
  Learning: "#9a7caa",
  "Profile pending": "#969687",
};
